version: "3.9"

services:
    rabbitmq:
        image: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
    worker:
        build: ./
        volumes:
            - ./:/app/
        depends_on:
            - rabbitmq
        command: celery -A tasks worker --loglevel=INFO
    flower:
        build: ./
        volumes:
            - ./:/app/
        ports:
            - 5555:5555
        command: celery -A tasks flower